name: release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        include:
          - rid: win-x64
            framework: net8.0-windows
          - rid: win-arm64
            framework: net8.0-windows
          - rid: linux-x64
            framework: net8.0
          - rid: osx-x64
            framework: net8.0
          - rid: osx-arm64
            framework: net8.0

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Publish
        run: dotnet publish "ModUploader.csproj" -c Release -f ${{ matrix.framework }} -r ${{ matrix.rid }} --self-contained false -p:PublishSingleFile=true -p:EnableWindowsTargeting=true -o "out/${{ matrix.rid }}"
      - name: Archive
        run: cd "out/${{ matrix.rid }}" && zip -r "${{ github.workspace }}/ModUploader-${{ matrix.rid }}.zip" .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ModUploader-${{ matrix.rid }}
          path: ModUploader-${{ matrix.rid }}.zip

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - uses: softprops/action-gh-release@v2
        with: 
          files: artifacts/**
          fail_on_unmatched_files: true
          draft: true
